Name:           ros-jade-ueye
Version:        0.0.7
Release:        0%{?dist}
Summary:        ROS ueye package

Group:          Development/Libraries
License:        BSD
URL:            http://wiki.ros.org/ueye
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-jade-camera-calibration-parsers
Requires:       ros-jade-cv-bridge
Requires:       ros-jade-dynamic-reconfigure
Requires:       ros-jade-image-transport
Requires:       ros-jade-nodelet
Requires:       ros-jade-roscpp
Requires:       ros-jade-std-msgs
BuildRequires:  ros-jade-camera-calibration-parsers
BuildRequires:  ros-jade-catkin
BuildRequires:  ros-jade-cv-bridge
BuildRequires:  ros-jade-dynamic-reconfigure
BuildRequires:  ros-jade-image-transport
BuildRequires:  ros-jade-nodelet
BuildRequires:  ros-jade-roscpp
BuildRequires:  ros-jade-roslaunch
BuildRequires:  ros-jade-rostest
BuildRequires:  ros-jade-std-msgs

%description
Driver for IDS Imaging uEye cameras.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jade/setup.sh" ]; then . "/opt/ros/jade/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/jade" \
        -DCMAKE_PREFIX_PATH="/opt/ros/jade" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jade/setup.sh" ]; then . "/opt/ros/jade/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/jade

%changelog
* Fri Dec 04 2015 Kevin Hallenbeck <kmhallen@oakland.edu> - 0.0.7-0
- Autogenerated by Bloom

* Wed Feb 11 2015 Kevin Hallenbeck <kmhallen@oakland.edu> - 0.0.6-0
- Autogenerated by Bloom

* Mon Feb 09 2015 Kevin Hallenbeck <kmhallen@oakland.edu> - 0.0.5-0
- Autogenerated by Bloom

* Sun Feb 08 2015 Kevin Hallenbeck <kmhallen@oakand.edu> - 0.0.4-0
- Autogenerated by Bloom

